name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write 

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Run semantic-release
        uses: cycjimmy/semantic-release-action@v5
        with:
          semantic_version: 19.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
