name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run semantic-release
        uses: cycjimmy/semantic-release-action@v5
        with:
          semantic_version: 19.0.5   # versão do semantic-release usada pela action (exemplo)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
